const express=require('express');const helmet=require('helmet');const cors=require('cors');const rateLimit=require('express-rate-limit');const multer=require('multer');const fs=require('fs/promises');const path=require('path');const os=require('os');const crypto=require('crypto');const {spawn}=require('child_process');
const app=express();
const PORT=Number(process.env.PORT||8787),MAX=50*1024*1024,ROOT=process.env.TMP_DIR||path.join(os.tmpdir(),'pexora');
const ORIGIN=process.env.ALLOWED_ORIGIN||true;const upload=multer({dest:path.join(ROOT,'uploads'),limits:{fileSize:MAX,files:1}});const limiter=rateLimit({windowMs:60000,max:20,standardHeaders:true,legacyHeaders:false});
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));app.use(cors({origin:ORIGIN}));app.use(express.json({limit:'1mb'}));app.use(limiter);app.disable('x-powered-by');
async function init(){await fs.mkdir(path.join(ROOT,'uploads'),{recursive:true});await fs.mkdir(path.join(ROOT,'out'),{recursive:true});}
function run(cmd,args,timeout=120000){return new Promise((resolve,reject)=>{const c=spawn(cmd,args,{stdio:['ignore','pipe','pipe']});let err='';c.stderr.on('data',d=>err+=d);const t=setTimeout(()=>{c.kill('SIGKILL');reject(new Error('Conversion timed out.'));},timeout);c.on('error',e=>{clearTimeout(t);reject(e)});c.on('close',code=>{clearTimeout(t);code===0?resolve():reject(new Error(err.slice(-1200)||`Process exited ${code}`));});});}
async function cleanup(...files){for(const f of files)if(f)await fs.rm(f,{force:true}).catch(()=>{});}
async function outputFile(ext){return path.join(ROOT,'out',crypto.randomUUID()+ext)}
async function sendFile(res,file,name,type){res.type(type||'application/octet-stream');res.download(file,name,()=>cleanup(file));}
app.get('/api/health',(req,res)=>res.json({ok:true,tools:['pdf-to-word','word-to-pdf','html-to-pdf','protect','unlock']}));
app.post('/api/convert/word-to-pdf',upload.single('file'),async(req,res)=>{const input=req.file?.path;if(!input)return res.status(400).json({error:'No DOC/DOCX file uploaded.'});const outDir=path.join(ROOT,'out',crypto.randomUUID());try{await fs.mkdir(outDir,{recursive:true});await run('soffice',['--headless','--convert-to','pdf','--outdir',outDir,input]);const files=await fs.readdir(outDir);const pdf=files.find(x=>x.toLowerCase().endsWith('.pdf'));if(!pdf)throw new Error('LibreOffice did not produce a PDF.');await sendFile(res,path.join(outDir,pdf),'converted.pdf','application/pdf');}catch(e){res.status(500).json({error:'Word to PDF conversion failed. Make sure LibreOffice is installed on the backend.'});}finally{await cleanup(input,outDir);}});
app.post('/api/convert/pdf-to-word',upload.single('file'),async(req,res)=>{const input=req.file?.path;if(!input)return res.status(400).json({error:'No PDF uploaded.'});const outDir=path.join(ROOT,'out',crypto.randomUUID());try{await fs.mkdir(outDir,{recursive:true});await run('soffice',['--headless','--convert-to','docx','--outdir',outDir,input]);const files=await fs.readdir(outDir);const doc=files.find(x=>x.toLowerCase().endsWith('.docx'));if(!doc)throw new Error('LibreOffice did not produce DOCX.');await sendFile(res,path.join(outDir,doc),'converted.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document');}catch(e){res.status(500).json({error:'PDF to Word conversion failed. Make sure LibreOffice is installed and supports PDF import/export.'});}finally{await cleanup(input,outDir);}});
app.post('/api/convert/html-to-pdf',async(req,res)=>{const html=String(req.body?.html||'');if(!html||html.length>2_000_000)return res.status(400).json({error:'HTML is empty or too large.'});const dir=path.join(ROOT,'out',crypto.randomUUID());const src=path.join(dir,'input.html'),pdf=path.join(dir,'output.pdf');try{await fs.mkdir(dir,{recursive:true});await fs.writeFile(src,html,'utf8');const chrome=process.env.CHROMIUM_PATH||'chromium';await run(chrome,['--headless','--no-sandbox','--disable-gpu','--disable-dev-shm-usage',`--print-to-pdf=${pdf}`,`file://${src}`],120000);await sendFile(res,pdf,'document.pdf','application/pdf');}catch(e){res.status(500).json({error:'HTML to PDF conversion failed. Set CHROMIUM_PATH to a Chromium/Chrome binary on the server.'});}finally{await cleanup(dir);}});
app.post('/api/pdf/security',upload.single('file'),async(req,res)=>{const input=req.file?.path,mode=req.body?.mode,password=String(req.body?.password||'');if(!input)return res.status(400).json({error:'No PDF uploaded.'});if(!['protect','unlock'].includes(mode)||!password)return res.status(400).json({error:'Choose protect/unlock and provide a password.'});const out=await outputFile('.pdf');try{if(mode==='protect')await run('qpdf',['--encrypt',password,password,'256','--',input,out]);else await run('qpdf',['--password='+password,'--decrypt',input,out]);await sendFile(res,out,mode==='protect'?'protected.pdf':'unlocked.pdf','application/pdf');}catch(e){res.status(500).json({error:mode==='protect'?'PDF protection failed. Make sure qpdf is installed.':'Unlock failed. Check the password and make sure qpdf is installed.'});}finally{await cleanup(input,out);}});
app.use(express.static(path.join(__dirname,'..')));init().then(()=>app.listen(PORT,()=>console.log(`Pexora backend running on http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
